### ISSUE TITLE
Does this package support Laravel 5.3?

### ISSUE THREAD

**Issue by roulendz** [Telerivet/telerivet-php-client#4]
Is there any news regarding PSR loading.

I would really like to use this package in laravel and more awesoem if as Laravel Notifications.

http://laravel-notification-channels.com/
https://laravel.com/docs/5.3/notifications

**Comment by chrisbjr** [comment]
Just release a Laravel Notifcation Channel for Telerivet here:

https://github.com/CoreProc/laravel-notification-channel-telerivet

**Comment by anasbadrusalam** [comment]
> Just release a Laravel Notifcation Channel for Telerivet here:
> 
> https://github.com/CoreProc/laravel-notification-channel-telerivet

Thank's a lot
