### ISSUE TITLE
Telerivet_CustomVars breaks in php 8 - method signatures do not match Iterator.

### ISSUE THREAD

**Issue by brianmerz** [Telerivet/telerivet-php-client#7]
I believe this is an easy fix, return types to the methods that are inherited from Iterator.

Example Error Message:
`Return type of Telerivet_CustomVars::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice`

`Filename: lib/entity.php`

**Comment by youngj** [comment]
Thanks for letting us know, should be fixed now.

**Comment by brianmerz** [comment]
You rock! Thanks!
